Clase Formulas: Herederas atributos deficiones

In [33]:
import math

class TrianguloEquilatero:
    def __init__(self, lado1, lado2, lado3):
        self.lado1 = lado1
        self.lado2 = lado2
        self.lado3 = lado3

    def calcular_area(self):
        """
        Calcula el área del triángulo equilátero.
        Fórmula: (raíz cuadrada de 3 / 4) * lado^2
        """
        return (math.sqrt(3) / 4) * self.lado1**2

    def calcular_perimetro(self):
        """
        Calcula el perímetro del triángulo equilátero.
        """
        return self.lado1 + self.lado2 + self.lado3

# Solicitar al usuario los valores de los lados
lado1 = float(input("Ingresa el valor del lado 1: "))
lado2 = float(input("Ingresa el valor del lado 2: "))
lado3 = float(input("Ingresa el valor del lado 3: "))

# Crear una instancia de la clase TrianguloEquilatero
triangulo = TrianguloEquilatero(lado1, lado2, lado3)

# Calcular área y perímetro
area = triangulo.calcular_area()
perimetro = triangulo.calcular_perimetro()

# Imprimir resultados
print(f"Área del triángulo: {area}")
print(f"Perímetro del triángulo: {perimetro}")

Ingresa el valor del lado 1: 10
Ingresa el valor del lado 2: 5
Ingresa el valor del lado 3: 8
Área del triángulo: 43.30127018922193
Perímetro del triángulo: 23.0


In [41]:
import random

class Matriz:
    def __init__(self, filas, columnas):
        self.filas = filas
        self.columnas = columnas
        self.matriz = [[0] * columnas for _ in range(filas)]

    def __str__(self):
        return "\n".join([" ".join(map(str, fila)) for fila in self.matriz])

class MatrizAleatoria(Matriz):
    def __init__(self, filas, columnas, rango_inicio, rango_fin):
        super().__init__(filas, columnas)
        self.generar_matriz_aleatoria(rango_inicio, rango_fin)

    def generar_matriz_aleatoria(self, rango_inicio, rango_fin):
        for i in range(self.filas):
            for j in range(self.columnas):
                self.matriz[i][j] = random.randint(rango_inicio, rango_fin)

matriz_aleatoria = MatrizAleatoria(4, 4, 1, 100)

print("Matriz Aleatoria:")
print(matriz_aleatoria)

Matriz Aleatoria:
71 78 66 7
18 71 6 39
30 45 9 62
69 32 66 23


In [40]:
import numpy as np

class Matriz:
    def __init__(self, matriz):
        self.matriz = matriz

    def __str__(self):
        return str(self.matriz)

class CalculadoraDeterminante(Matriz):
    def __init__(self, matriz):
        super().__init__(matriz)

    def calcular_determinante(self):
        try:
            determinante = np.linalg.det(self.matriz)
            return determinante
        except np.linalg.LinAlgError:
            return "La matriz no es cuadrada, no se puede calcular el determinante."

matriz_ejemplo = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

matriz_calculadora = CalculadoraDeterminante(matriz_ejemplo)

resultado = matriz_calculadora.calcular_determinante()

print(f"Matriz:\n{matriz_calculadora}\nDeterminante: {resultado}")

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinante: 0.0
